version: "3"

volumes:
  data:

services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    networks:
      - app-network

  nextjs:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
